In [12]:
#1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np 
# data = (np.arange(10)==4).astype(int)
# data

#or 
b=np.array([int(x==4) for x in range(10)])
print(b)

[0 0 0 0 1 0 0 0 0 0]


In [13]:
#2. Create a vector with values ranging from 10 to 49.
import numpy as np 
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np 
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np 
a = [1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [42]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
# import numpy as np 
# a = np.random.randint(0,100,(10,10))
# a

#or
import numpy as np 
from numpy import random
b = np.random.randint(0,10,(10,10))
b

array([[3, 7, 3, 2, 4, 6, 0, 3, 3, 5],
       [7, 4, 7, 2, 4, 7, 0, 1, 4, 4],
       [8, 2, 6, 9, 8, 8, 1, 3, 3, 6],
       [5, 6, 5, 1, 8, 9, 6, 4, 5, 7],
       [2, 4, 9, 7, 4, 7, 0, 4, 2, 4],
       [9, 0, 8, 0, 2, 9, 1, 6, 2, 9],
       [9, 5, 2, 4, 5, 1, 2, 9, 0, 6],
       [2, 2, 7, 6, 0, 0, 6, 6, 6, 9],
       [4, 9, 7, 4, 7, 2, 0, 8, 3, 8],
       [5, 1, 1, 4, 9, 0, 9, 6, 8, 3]])

98

In [31]:
a.min()

1

In [45]:
#6. Create a random vector of size 30 and find the mean value.
import numpy as np 
x = np.random.random(30)
x

array([0.12017333, 0.86082374, 0.57048857, 0.08773201, 0.11321429,
       0.21322012, 0.50176202, 0.61198977, 0.54070071, 0.61129126,
       0.77719354, 0.05078959, 0.17421883, 0.37890066, 0.26595344,
       0.423814  , 0.71994918, 0.78620518, 0.49364508, 0.95114926,
       0.47991511, 0.74416697, 0.23994942, 0.35944749, 0.41217299,
       0.19293079, 0.52678584, 0.24421759, 0.71243803, 0.91437656])